### ISSUE TITLE
drill ERROR: Log directory does not exist or is not writable: /var/lib/drill/log 

### ISSUE THREAD

**Issue by clement-igonet** [wearefrank/charts#22]
When using default latest, or explicit 1.3.4, 1.3.0 or 1.2.13 versions, and when starting with these helm values (1), I got a blocking message (2):

# 1
```yaml
persistence:
  enabled: true
```

# 2
```
drill ERROR: Log directory does not exist or is not writable: /var/lib/drill/log 
```

An idea about how to deal with this issue ???

**Comment by philipsens** [comment]
Thank you for reporting an issue. We will try to replicate and fix it. In the mean time, could you tell us if you used a dynamic provisioner or an existing claim?

Some issues (like this one) slip trough and are fixed over time, so I allways recomment using the latest one.

**Comment by clement-igonet** [comment]
> Thank you for reporting an issue. We will try to replicate and fix it. In the mean time, could you tell us if you used a dynamic provisioner or an existing claim?
> 
> 
> 
> Some issues (like this one) slip trough and are fixed over time, so I allways recomment using the latest one.

Dynamic provisioner (OVH)

**Comment by alisihab** [comment]
this was fixed by https://github.com/wearefrank/charts/pull/28

**Comment by philipsens** [comment]
Thank you @alisihab
