### ISSUE TITLE
Apache Drill affinity

### ISSUE THREAD

**Issue by shanehughes1990** [wearefrank/charts#9]
I was deploying Apache Drill to cluster and noticed my affinity values were not taking affect,

I went searching through the helm template https://github.com/wearefrank/charts/blob/main/charts/drill/templates/statefulset.yaml#L27 and it seems the template does not use .Values.affinity anywhere in the statefulset.yaml

**Comment by philipsens** [comment]
Thank you for bringing up this issue.

It sounds like a problem that's easy to fix. 

I'll soon take a look at it.

**Comment by philipsens** [comment]
This issue is fixed in release [drill-1.2.12](https://github.com/wearefrank/charts/releases/tag/drill-1.2.12)
